goog.provide('frontend.api.client');
frontend.api.client.health_check = (function frontend$api$client$health_check(){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/health"),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("health","loaded","health/loaded",-60084697)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("health","failed","health/failed",-209586366)], null)], null);
});
frontend.api.client.get_recordings = (function frontend$api$client$get_recordings(){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings"),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("library","recordings-loaded","library/recordings-loaded",-1193177927)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("library","recordings-failed","library/recordings-failed",1762644042)], null)], null);
});
frontend.api.client.get_recording_info = (function frontend$api$client$get_recording_info(id){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("recording","info-loaded","recording/info-loaded",-1486213417)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("recording","info-failed","recording/info-failed",1254243563)], null)], null);
});
frontend.api.client.delete_recording = (function frontend$api$client$delete_recording(id){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"delete","delete",-1768633620),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("library","recording-deleted","library/recording-deleted",-694082837)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("library","recording-delete-failed","library/recording-delete-failed",-2040482149)], null)], null);
});
frontend.api.client.upload_recording = (function frontend$api$client$upload_recording(file){
var form_data = (new FormData());
form_data.append("file",file);

return new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/upload"),new cljs.core.Keyword(null,"body","body",-2049205669),form_data,new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("upload","success","upload/success",984925585)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("upload","failure","upload/failure",2094840442)], null),new cljs.core.Keyword(null,"on-progress","on-progress",1196110410),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("upload","progress","upload/progress",-1600913698)], null)], null);
});
frontend.api.client.analysis_params__GT_body = (function frontend$api$client$analysis_params__GT_body(params){
var body = (function (){var G__27427 = cljs.core.PersistentArrayMap.EMPTY;
var G__27427__$1 = (cljs.core.truth_(new cljs.core.Keyword(null,"start-time","start-time",814801386).cljs$core$IFn$_invoke$arity$1(params))?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__27427,new cljs.core.Keyword(null,"startTime","startTime",1583467878),new cljs.core.Keyword(null,"start-time","start-time",814801386).cljs$core$IFn$_invoke$arity$1(params)):G__27427);
var G__27427__$2 = (cljs.core.truth_(new cljs.core.Keyword(null,"end-time","end-time",-1849817460).cljs$core$IFn$_invoke$arity$1(params))?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__27427__$1,new cljs.core.Keyword(null,"endTime","endTime",-662648598),new cljs.core.Keyword(null,"end-time","end-time",-1849817460).cljs$core$IFn$_invoke$arity$1(params)):G__27427__$1);
var G__27427__$3 = (cljs.core.truth_(new cljs.core.Keyword(null,"topN","topN",807743645).cljs$core$IFn$_invoke$arity$1(params))?cljs.core.assoc_in(G__27427__$2,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.Keyword(null,"topN","topN",807743645)], null),new cljs.core.Keyword(null,"topN","topN",807743645).cljs$core$IFn$_invoke$arity$1(params)):G__27427__$2);
var G__27427__$4 = (cljs.core.truth_(new cljs.core.Keyword(null,"package-prefix","package-prefix",862933941).cljs$core$IFn$_invoke$arity$1(params))?cljs.core.assoc_in(G__27427__$3,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.Keyword(null,"packagePrefix","packagePrefix",87835874)], null),new cljs.core.Keyword(null,"package-prefix","package-prefix",862933941).cljs$core$IFn$_invoke$arity$1(params)):G__27427__$3);
if(cljs.core.truth_(new cljs.core.Keyword(null,"thread-name","thread-name",1811701974).cljs$core$IFn$_invoke$arity$1(params))){
return cljs.core.assoc_in(G__27427__$4,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.Keyword(null,"threadName","threadName",-2027831604)], null),new cljs.core.Keyword(null,"thread-name","thread-name",1811701974).cljs$core$IFn$_invoke$arity$1(params));
} else {
return G__27427__$4;
}
})();
return JSON.stringify(cljs.core.clj__GT_js(body));
});
frontend.api.client.run_analysis = (function frontend$api$client$run_analysis(id,type,params){
return new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)+"/analyze/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(cljs.core.name(type))),new cljs.core.Keyword(null,"body","body",-2049205669),frontend.api.client.analysis_params__GT_body(params),new cljs.core.Keyword(null,"headers","headers",-835030129),new cljs.core.PersistentArrayMap(null, 1, ["Content-Type","application/json"], null),new cljs.core.Keyword(null,"response-format","response-format",1664465322),ajax.core.json_response_format(new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"keywords?","keywords?",764949733),true], null)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("analysis","result","analysis/result",325641471)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("analysis","failed","analysis/failed",-406541374)], null)], null);
});
frontend.api.client.run_analysis_async = (function frontend$api$client$run_analysis_async(id,type,params){
return new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)+"/analyze/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(cljs.core.name(type))+"/async"),new cljs.core.Keyword(null,"body","body",-2049205669),frontend.api.client.analysis_params__GT_body(params),new cljs.core.Keyword(null,"headers","headers",-835030129),new cljs.core.PersistentArrayMap(null, 1, ["Content-Type","application/json"], null),new cljs.core.Keyword(null,"response-format","response-format",1664465322),ajax.core.json_response_format(new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"keywords?","keywords?",764949733),true], null)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("analysis","async-started","analysis/async-started",-1117435448)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("analysis","failed","analysis/failed",-406541374)], null)], null);
});
frontend.api.client.get_job_status = (function frontend$api$client$get_job_status(id,job_id){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)+"/analyze/jobs/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(job_id)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("job","update","job/update",1045618437)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("job","status-failed","job/status-failed",1339370171)], null)], null);
});
frontend.api.client.connect_sse = (function frontend$api$client$connect_sse(id,job_id){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"url","url",276297046),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/recordings/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(id)+"/analyze/jobs/"+cljs.core.str.cljs$core$IFn$_invoke$arity$1(job_id)+"/stream"),new cljs.core.Keyword(null,"on-message","on-message",1662987808),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("job","sse-message","job/sse-message",-1294649592)], null),new cljs.core.Keyword(null,"on-error","on-error",1728533530),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("job","sse-failed","job/sse-failed",-1664316261)], null),new cljs.core.Keyword(null,"on-open","on-open",-1391088163),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("job","sse-opened","job/sse-opened",209553114)], null)], null);
});
frontend.api.client.run_comparison = (function frontend$api$client$run_comparison(baseline_id,target_id){
return new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"method","method",55703592),new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword(null,"uri","uri",-774711847),(""+cljs.core.str.cljs$core$IFn$_invoke$arity$1(frontend.config.api_url)+"/compare/structured"),new cljs.core.Keyword(null,"body","body",-2049205669),JSON.stringify(cljs.core.clj__GT_js(new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"baselineRecordingId","baselineRecordingId",-751663510),baseline_id,new cljs.core.Keyword(null,"comparisonRecordingId","comparisonRecordingId",490442984),target_id], null))),new cljs.core.Keyword(null,"headers","headers",-835030129),new cljs.core.PersistentArrayMap(null, 1, ["Content-Type","application/json"], null),new cljs.core.Keyword(null,"response-format","response-format",1664465322),ajax.core.json_response_format(new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"keywords?","keywords?",764949733),true], null)),new cljs.core.Keyword(null,"on-success","on-success",1786904109),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("comparison","result","comparison/result",-507401234)], null),new cljs.core.Keyword(null,"on-failure","on-failure",842888245),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("comparison","error","comparison/error",1926451741)], null)], null);
});

//# sourceMappingURL=frontend.api.client.js.map
